### ISSUE TITLE
C-Dina 代码

### ISSUE THREAD

**Issue by cloudspurs** [bigdata-ustc/EduCDM#18]
## Description
根据Dina修改的C-Dina代码

## References
A Cognitive Diagnosis Model for Continuous Response

**Comment by tswsxk** [comment]
Hi, cloudspurs, are you going to contribute the code descripted in "A Cognitive Diagnosis Model for Continuous Response"?

**Comment by cloudspurs** [comment]
对

**Comment by tswsxk** [comment]
We are glad to hear that. Maybe you can first put forward a new issue with the "Feature request" template, where some necessary information is required which can help us understand your plan.
