### ISSUE TITLE
代码运行中遇到的问题

### ISSUE THREAD

**Issue by 1212312341234** [bigdata-ustc/EduCDM#35]
请问您的educdm代码怎么运行的，readme过于简单了，其中没有说明项目的运行（比如IRR的项目）

**Comment by 1212312341234** [comment]
How does your educdm code work? Readme is too simple and does not explain the operation of the project (such as IRR project)

**Comment by LegionKing** [comment]
We have included use cases in EduCDM/examples/. Each model is provided with examples of how to run the corresponding codes.

**Comment by 1212312341234** [comment]
Our team would like to invite you to join us in applying for Alibaba cloud's collaborative education project. The theme is about smart education. Would you like to provide us with guidance?

**Comment by tswsxk** [comment]
Maybe you could provide more information about your project? And I am not sure what guidance you need, maybe you could describe it with more details.

**Comment by 1212312341234** [comment]
Is it convenient for you to add a wechat

**Comment by 1212312341234** [comment]
We hope to apply for Alibaba cloud collaborative education project to build Python based education big data mining course on Tianchi AI training platform. Because your laboratory has a deep research foundation in this field, we hope you can join us to apply for the project and build the course，This is the course we previously built on Tianchi AI training platform: "statistical decision-making methods and Applications" course link: https://tianchi.aliyun.com/ailab/invite/course/32nxMrHHjOHD3fW4IZCGyJ4h5F0o8GiuvMvvXl8F

**Comment by tswsxk** [comment]
Maybe we could talk more details in wechat. You can send your wechat to my email tongsw@mail.ustc.edu.cn.
