### ISSUE TITLE
About the preprocess of datasets

### ISSUE THREAD

**Issue by DevilYangS** [bigdata-ustc/EduCDM#36]
您好，
非常感谢你们的出色的工作！
我有一个关于数据集 的问题：
请问Edudata中的‘a0910’数据集 是 处理自 ‘2009-2010 ASSISTment Skill Builder Data’ 吗？
我处理得到数据 和 这个数据集的 有一点不同，而且和NCD，RCD的数据集也不太相同。
请问是否方便提供数据预处理的脚本，谢谢

**Comment by tswsxk** [comment]
Hi, there, if you have any problem about EduData, please raise the issue in the repo EduData.
