### ISSUE TITLE
Where to download the dataset

### ISSUE THREAD

**Issue by Twinkle6070** [bigdata-ustc/EduCDM#54]
Hello, may I ask where to download the datasets used in the examples/FuzzyCDF. py program, such as "../../data/math2015/math1/obj_derb_index. csv" and "../../data/math2015/math1/sub_derb_index. csv"

**Comment by LegionKing** [comment]
Hello. Please refer to examples/FuzzyCDF/prepare_dataset.ipynb.

**Comment by Twinkle6070** [comment]
来信已收到，我会及时处理，谢谢！

**Comment by Twinkle6070** [comment]
> 来信已收到，我会及时处理，谢谢！



> Hello. Please refer to examples/FuzzyCDF/prepare_dataset.ipynb.

ok，thank you very much！

**Comment by Twinkle6070** [comment]
来信已收到，我会及时处理，谢谢！
