### ISSUE TITLE
KaNCD not found

### ISSUE THREAD

**Issue by WangshilongChina** [bigdata-ustc/EduCDM#55]
from EduCDM import KaNCD
ImportError: cannot import name 'KaNCD' from 'EduCDM'
请问库内没有更新吗？

**Comment by LegionKing** [comment]
> from EduCDM import KaNCD ImportError: cannot import name 'KaNCD' from 'EduCDM' 请问库内没有更新吗？

Hello！感谢提醒。pypi上还没更新，所以pip install EduCDM的方式下载的不是最新版本。可以先使用ReadMe文件里提供的另一种方式来安装，即先clone本库到本地，在本地安装。pypi上也会在近期更新。

此外，我们正在重构本库，使代码结构更统一，使用更方便。过段时间后会发布，欢迎关注和使用。

**Comment by LegionKing** [comment]
Update: PyPI上版本已更新，可通过pip install EduCDM安装
